# Generated by Django 5.1.4 on 2025-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/upload/'),
        ),
    ]
